### ISSUE TITLE
dev-python/dtschema: missing dependencies

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [rodan/overlay#1]
Running `dt-doc-validate` produces the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/dt-doc-validate", line 5, in <module>
    from dtschema.doc_validate import main
  File "/usr/lib/python3.12/site-packages/dtschema/__init__.py", line 23, in <module>
    from dtschema.schema import (
  File "/usr/lib/python3.12/site-packages/dtschema/schema.py", line 7, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
```
After installing `dev-python/ruamel-yaml`:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/dt-doc-validate", line 5, in <module>
    from dtschema.doc_validate import main
  File "/usr/lib/python3.12/site-packages/dtschema/__init__.py", line 35, in <module>
    import dtschema.dtb
  File "/usr/lib/python3.12/site-packages/dtschema/dtb.py", line 8, in <module>
    import libfdt
ModuleNotFoundError: No module named 'libfdt'
```
Which is fixed by installing `dev-python/pylibfdt`
ebuild `dev-python/dtschema-2023.11:0`

**Comment by rodan** [comment]
thank you for pointing out the missing dependencies.
